# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20171108_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='所属组'),
        ),
    ]
